server: 
    prot: 8201
spring: 
    profiles: dev
    application: 
        name: spring-config-8201
eureka: 
    client: 
        service-url: 
            defaultZone: http://eureka-dev.com:7001/eureka/
            
            
 ---
 server: 
    prot: 8202
 spring: 
    profiles: test
    application: 
        name: spring-config-8202
 eureka: 
    client: 
        service-url: 
         defaultZone: http://eureka-test.com:7001/eureka/